config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"
  get "/", to: "welcome#index"
  get "/payments/session", to: "payments#get_stripe_id"
  get "/payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"

  devise_for :users
  resources :users 
  resources :carts, only: [:create, :index, :destroy]

  
  resources :listings
  get "/search", to: "listings#search", as: "search"
  
end
 

app/models/listing.rb
class Listing < ApplicationRecord
  # Listing model relations
  belongs_to :category
  belongs_to :munit
  belongs_to :user
  # validations for listings
  validates :title, :price, :quantity, :munit, :category, presence: true
  # This will allow user to attach a photo to each listing
  has_one_attached :photo
  # set up many to many relation between listing and cart through join table

  # listing cannot be deleted alone as it is referenced in join table as well, this will delete the listing's record from join table and will leave no orphaned record
  has_many :cart_listings, dependent: :delete_all
  has_many :carts, through: :cart_listings
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  # Allow users to view index, show and search page only if they are not signed in
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_listing, only: [:show,  :edit, :update, :destroy]
  before_action :set_categories_and_munits, only: [:new, :edit, :create]

  # this will load the code in the ability model(cancancan)
  load_and_authorize_resource

  def search
    # search method will allow users to search for a listing by it's title
    if params[:q].blank?

      flash[:alert] = "Field cannot be left blank"
      redirect_to root_path
    else
      @params = params[:q].downcase

      @listings_found = Listing.where("lower(title) LIKE?", "%" + "#{@params}" + "%")

    end
  end

  def index
    # show all listings
    @listings = Listing.all
  end

  def create
    # create a listing for current user
    @listing = current_user.listings.create(listing_params)

    if @listing.errors.any?
      render "new"
    else
      redirect_to @listing
    end
  end

  def new
    @listing = Listing.new
  end

  def show
    # show a single listing
  end

  def edit
  end

  def update
    # update the current listing
    @listing.update(listing_params)
    redirect_to @listing
  end

  def destroy
    # deleted current listing
    @listing.destroy
    redirect_to listings_path
  end

  private

  # Find the listing from database with matching id and store that in a variable
  def set_listing
    id = params[:id]
    @listing = Listing.find(id)
  end

  # Store all categories and measurement units in variables so that they can be used in creating drop downs in form partial
  def set_categories_and_munits
    @categories = Category.all
    @munits = Munit.all
  end

  # strong parameters allow user to create listing with explicitly permitted parameters
  def listing_params
    params.require(:listing).permit(:title, :description, :price, :quantity, :category_id, :munit_id, :photo)
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<% if listing.errors.any? %>
      <% listing.errors.full_messages.each do |error| %>
          <p><%= error %> </p>
      <% end %>
<% end %> 


<%= form_with model: listing, local: true do |form| %>
<form>
<div class="row">
  <div class="col-md-4">
  <%= form.label :title %>
  <%= form.text_field :title, class:"form-control" %>
  </div>
</div>



<div class="row">
  <div class="col-md-4">
  <%= form.label :price %>
  <%= form.number_field :price, min: 0, class:"form-control"%>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
  <%= form.label :quantity %>
  <%= form.number_field :quantity, min: 0,class:"form-control" %>
  </div>
</div>

<div class="form-group">
  
  <%= form.label :category %>
  <%= form.collection_select :category_id, categories, :id, :name, include_blank: true
  %>
  
</div>

<div class="form-group">
  <%= form.label :measurement_unit %>
  <%= form.collection_select :munit_id, munits, :id, :name, include_blank: true
  %>
</div>

<div class="row">
  <div class="col-md-6">
  <%= form.label  :description%>
  <%= form.text_area :description,class:"form-control" %>
  </div>
</div>

<div class="form-group row">  
<div class=" col-md-4 ">
  <%= form.label :photo %> 
  <%= form.file_field :photo, accept: 'image/png,image/gif,image/jpeg,image/jpg' %>
</div>
  
</div>

<div>
  <%= form.submit %>
</div>
<% end %>
</form>

app/views/listings/_set-img.html.erb
<%# logic for displaying image uploaded by user and if no image is displayed, default image should be displayed %>
<% if listing.photo.attached? %>
        <%= image_tag listing.photo %>
      <% else %>
        <%= image_tag "mix-veg.png" %>
<% end %>

app/views/listings/edit.html.erb
<h3>Edit a Listing</h3>

<%= render "form", listing: @listing, categories: @categories, 
munits: @munits %>

app/views/listings/index.html.erb
<div class="container"> 
  <h3>Welcome To FarmerSmart</h3>

    <div class = "row justify-content-around">
      <% @listings.each do |listing| %>
    <%# rendered the partial for displaying image uploaded by user and if no image is displayed, default image will be displayed %>
      
        <div class="card text-center my-3 col-md-4 col-xs-12" style="max-width: 30%; min-width: 18rem;" >
        <div class="card-body-index">
         <div class="img-index" >
            <%= render "set-img",  listing: listing %>
         </div> 
        
        <h5><%= listing.title %></h5>
        <p>Price:<%=number_to_currency(listing.price)%></p>
        <p>Quantity:<%=listing.munit.name  %></p>
        <p>Category:<%=listing.category.name  %></p>
        <%# <%= link_to "View", listing %> 
        <%= button_to "View", listing, method: :get, class: "btn btn-primary" %>

      
        </div>
      </div>
      <% end %> 
      </div>
</div>


      
      
      
    

app/views/listings/new.html.erb
<h3>Create a Listing</h3>

<%= render "form", listing: @listing, categories: @categories, 
munits: @munits %>

app/views/listings/search.html.erb
<div class="container"> 
<h3>Search Results</h3>

 
<div class = "row justify-content-around">
   <% @listings_found.each do |listing| %>
   <div class="card text-center my-3 col-md-4 col-xs-12" style="max-width: 30%; min-width: 18rem;" >
   <%# rendered the partial for displaying image uploaded by user and if no image is displayed, default image will be displayed %>
    <div class="card-body-index">
     <div class="img-index">
       <%= render "set-img", listing: listing %>
     </div>
    <h4><%= listing.title %></h4>
    <p>Price:<%=number_to_currency(listing.price)%></p>
    <p>Quantity:<%=listing.munit.name  %></p>
    <p>Category:<%=listing.category.name  %></p>
     
    <%= button_to "view", listing, method: :get, class: "btn btn-primary" %>
    </div>
  </div>
    
 <% end %> 
</div>
</div>

    
   
    
  

app/views/listings/show.html.erb
 
  <div class="container"> 


<div class="card  my-3 col-md-4 col-xs-12" style="max-width: 40%; min-width: 18rem; margin: 0 auto;" >
<%# rendered the partial for displaying image uploaded by user and if no image is displayed, default image should be displayed %>
  <div class="card-body-show">
    <div class="show-img">
      <%= render "set-img", listing: @listing %>
    </div>  
    <h5><%= @listing.title %></h5>
    <p>Price:<%=number_to_currency(@listing.price)%></p>
    <p>Quantity:<%=@listing.munit.name  %></p>
    
    <p>Category:<%=@listing.category.name  %></p>
    <p>Description:<%=@listing.description  %></p>
    <h6>Location: <%= @listing.user.address.suburb %>
    
    <%# logic for displaying the links only if user in signed in and listing does not belongs to current user     %>
    <div>
          <%= link_to "Visit the farm", user_path(@listing.user.id)  %><br>
      <% if user_signed_in? && @listing.user.id != current_user.id %>
         
      <%# listing_id: @listing.id), method: :post have been added to link because by default link is get request and in this case we are adding a listing to cart which is a post request      %>

        <%= link_to carts_path(listing_id: @listing.id), method: :post,  class: 'btn btn-light ml-1 mb-1' do %>
          <%= image_tag 'cart.png', size: '30x30' %>
        <% end %> 
      <% end %>  

         

    </div>

       
        

    <div class="show-edit-delete">
    <% if can? :edit, @listing %>
      <%= link_to "Edit",  edit_listing_path(@listing.id) %>
      <%= link_to "Delete", listing_path(@listing.id), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    </div>
     
</div>
<%= link_to "Back", :back %>
</div>


      


   